# config/routes/attributes.yaml

# This configuration tells Symfony to look for routes defined as attributes in any PHP class stored in the src/Controller/ directory.

controllers:
    resource: ../../src/Controller/
    type: attribute

kernel:
    resource: ../../src/Kernel.php
    type: attribute
