<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>PlayWith</title>
        <!-- CSS Du site-->
        <head>
            <!--ROBOTO-->
            <link rel="preconnect" href="https://fonts.googleapis.com">
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
            <link href="https://fonts.googleapis.com/css2?family=Oswald&family=Roboto:wght@400;700&display=swap" rel="stylesheet">
            
            <!--Poppins-->
            <link rel="preconnect" href="https://fonts.googleapis.com">
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
            <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
            <!--CSS-->
            <link rel="stylesheet" href="../blog/static/style.css">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
        <!-- carousel -->
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
            
      </head>
    <body>
        <header class="site-header">
                <section class="top-nav">
                    <!--<div>
                        <img src='..\blog\images\Playwith.png' class="brand" alt='PlayWith'></a>
                    </div>-->
                        <input id="menu-toggle" type="checkbox" />
                            <label class='menu-button-container' for="menu-toggle">
                                <div class='menu-button'></div>
                            </label>
                                <ul class="menu">
                                        <li class="nav__item"><a href="#">Accueil</a></li>
                                        <li class="nav__item"><a href="#">Blog</a></li>
                                        <li class="nav__item"><a href="#">Boutique</a></li>
                                        <li class="nav__item"><a href="#">Forum</a></li>
                                        <li class="nav__item"><a href="#">Nous contacter</a></li>
                                </ul>
                 </section>
            
        </header>       
            <!--<div id="icons">
                <a href="http://www.twitter.fr"><i class="fab fa-twitter iconz"></i></a>
                <a href="http://www.instagram.fr"><i class="fab fa-instagram iconz"></i></a>
                <a href="http://www.facebook.fr"><i class="fab fa-facebook iconz"></i></a>
            </div>-->       
        <main>
            <?php 
            include('templates/homeView.php') ?> 
        </main>  
        <footer>
            <section>
                <div id='deuxiemeTrait'></div>
                
                    <div id="icons">
                        <a href="http://www.twitter.fr"><i class="fab fa-twitter"></i></a>
                        <a href="http://www.instagram.fr"><i class="fab fa-instagram"></i></a>
                        <a href="http://www.facebook.fr"><i class="fab fa-facebook"></i></a>
                    </div>
                    
                    <div id='copyright'>
                        <span>@ copyright sheepStories(); 2020</span>
                        <span> GitHub - rageQuitt </span>
                    </div>
                </div>
            </section>
        </footer>
        
    </body>
    <script src="..\blog\static\main.js">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    
</html>